version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: voice-timelogger-agent:latest
    container_name: voice-timelogger-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./tmp:/app/tmp
      - ./credentials:/app/credentials
    env_file:
      - .env
    environment:
      - DEBUG=false
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - TEMP_DIR=/app/tmp/meeting_recordings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  n8n:
    image: n8nio/n8n:latest
    container_name: voice-timelogger-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - api

volumes:
  tmp_data:
    driver: local
  n8n_data:
    driver: local